### ISSUE TITLE
Item Highlight Not Working Properly - v1.5.4

### ISSUE THREAD

**Issue by xrande** [kosace/EnhancePoEApp#378]
Using version 1.5.4. I have mine set to Item by Item.

The highlight chose the first chest armor. I moved it to my inventory, but it does not highlight the next item but instead the red overlay just stays there.

![image](https://user-images.githubusercontent.com/81092399/168805897-a37f0361-51cd-4102-bfed-47df3c29a501.png)

**Comment by AmenLi** [comment]
same, also have a error
![QQ图片20220517221054](https://user-images.githubusercontent.com/5909257/168831473-3a5cbdf7-5363-4f3b-a01d-9fd688f71112.png)
and this error pops up a dozen times until the computer freezes and the game freezes

**Comment by HiMarioLopez** [comment]
> Using version 1.5.4. I have mine set to Item by Item.
> 
> The highlight chose the first chest armor. I moved it to my inventory, but it does not highlight the next item but instead the red overlay just stays there.
> 
> ![image](https://user-images.githubusercontent.com/81092399/168805897-a37f0361-51cd-4102-bfed-47df3c29a501.png)

As per https://github.com/kosace/EnhancePoEApp/issues/324

Can you try running both our tool and PoE in Admin mode? Thanks.

Also @AmenLemon I'm deleting your comment because it's unrelated to the current issue, but I want you to know I am indeed looking at it. Thanks!

**Comment by HiMarioLopez** [comment]
Actually going to close this issue as it is a duplicate. If you have more insight to add to the issue after trying the proposed work around (Both in Admin mode), please post a comment under #324 , thanks!
