### ISSUE TITLE
[Bug] [Overlay] Unhandled NullReferenceException in Coordinates.CheckForHeaderHit causing client hang-up

### ISSUE THREAD

**Issue by HiMarioLopez** [kosace/EnhancePoEApp#381]
have a error
![QQ图片20220517221054](https://user-images.githubusercontent.com/5909257/168831473-3a5cbdf7-5363-4f3b-a01d-9fd688f71112.png)
and this error pops up a dozen times until the computer freezes and the game freezes

_Originally posted by @AmenLemon in https://github.com/kosace/EnhancePoEApp/issues/378#issuecomment-1128923608_

**Comment by Jaxxas** [comment]
I believe I've root caused this, it happens when the user closes the overlay while fetching with the stash tab overlay open. I have a fix on my fork.

PR: https://github.com/kosace/EnhancePoEApp/pull/386

**Comment by HiMarioLopez** [comment]
https://github.com/kosace/EnhancePoEApp/pull/386 Merged in after testing locally, I was no longer able to re-produce the crash with your code.

Thanks a ton for your contribution @ttgx1000 !
